[tool.volt]
log_level = "INFO"
allowed_hosts = [
    "volt.trkl.dev",
    "trkl.dev",
]
debug = false

[tool.volt.dev]
log_level = "DEBUG"
template_auto_reload = true
allowed_hosts = [
    "localhost:1234",
    "127.0.0.1:1234",
]
server_address = "127.0.0.1"
server_port = 1234
debug = true

[tool.volt.production]
server_host = "0.0.0.0"
server_port = 8080

[tool.ruff]
line-length = 120
